version: '3'
services:
  emby-telegram-notifier:
    container_name: emby-telegram-notifier
    image: guzmi/emby-telegram-notifier
    restart: always
    ports:
      - "5000:5000"
    environment:
      - EMBY_BASE_URL=
      - EMBY_API_KEY=
      - TELEGRAM_BOT_TOKEN=
      - TELEGRAM_CHAT_ID=
      - SEASON_ADDED_WITHIN_X_DAYS=7
      - EPISODE_PREMIERED_WITHIN_X_DAYS=3